ash-jc-allen/short-url

src/Classes/Resolver.php
tests/Unit/Classes/ResolverTest.php

This fixes a bug that allowed multiple visits to a single-use URL if the tracking was disabled.
Issue: #22

Single-use URL bug fix

---

config/short-url.php
src/Classes/Builder.php
src/Classes/Validation.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Classes/ValidationTest.php

I don't know if it's more appropriate if we set the new config variable to true by default.

Added a config option to allow enforce https in the destination URL

---

src/Providers/ShortURLProvider.php

Currently if you run `php artisan vendor:publish` the package configs are marked as a generic `config`. 
God knows how many packages are tagged like this but after this PR the publish command is specific onto which package you are publishing

Updated tags

---

composer.json
src/Facades/ShortURL.php
src/Facades/ShortURLBuilder.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/TestCase.php

This addresses issue #44. It deprecates the existing ``` ShortURLBuilder ``` facade in favour of a newer ``` ShortURL ``` facade.

Add new ShortURL facade.

---

database/migrations/2020_04_10_224546_update_short_url_table_for_version_three_zero_zero.php
src/Classes/Builder.php
src/Classes/Resolver.php
src/Facades/ShortURL.php
src/Models/ShortURL.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Controllers/ShortURLControllerTest.php

This adds the functionality to activate and deactivate short URLs. This could be useful for marketing campaigns where the marketer only wants the URL live within a certain timeframe.

Adds activated_at and deactivated_at dates.

---

README.md
config/short-url.php
src/Providers/ShortURLProvider.php

This PR makes the config validation optional. Previously the config was always validated but this could cause some issues if the config had been cached before installing.
There's now a new config value called ``` validate_config ``` that can be used to toggle the validation.
Addresses: https://github.com/ash-jc-allen/short-url/issues/49

Optional config validation

---

.travis.yml
README.md
composer.json

This PR removes support for Laravel 5.8 and makes the Laravel 6 the minimum required version.

Remove Laravel 5.8 support

---

tests/Unit/Classes/BuilderTest.php
tests/Unit/Models/ShortURL/TrackingFieldsTest.php

- Using the `assertSame` to make assertion equals strictly.
- Migrate PHPUnit configuration file to resolve following message:
```
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.13
Configuration: /home/peterli/short-url/phpunit.xml
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```

Migrate PHPUnit setting and using assertSame

---

src/Classes/Builder.php
src/Facades/ShortURL.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Controllers/ShortURLControllerEmptyPrefixTest.php

This PR adds the ability to create short URLs with an empty prefix.
If the `short-url.prefix` config field is set to `null`, a prefix won't be used in the default short URL when it's stored in the database.
I've not made any changes to the default route in `web.php` because it appears that Laravel strips double forward slashes, so we don't need to handle this ourselves (as far as I can tell).

Added ability to remove the prefix from default short URLs

---

src/Classes/Builder.php

This PR adds a `toArray()` method into the Builder class. Currently, all Builder properties are protected and so are the methods responsible for populating default values for many of them. Adding the `toArray()` methods adds a convenient way of exposing that data without having to change any Builder class property or method visibility.
My specific use case for this was the need to create new ShortURL records without using Builder. When using Laravel Nova, the model `create()` method is invoked however many of the ShortURL model fields are set using logic in the Builder class not in the model itself. I wrote a model observer that listens for the ShortURL::creating event to be raised by Nova. I wanted to use the logic in Builder to allow me to populate missing fields during creation. Adding …

feat: Add Builder::toArray() method

---

README.md
src/Classes/Builder.php
tests/Unit/Classes/BuilderTest.php

This PR adds support for using `when` to chain methods in the `Builder` like so:
```php
$shortUrl = (new Builder())
->when(
$flag,
fn (Builder $builder): Builder => $builder->destinationUrl('https://domain.com'),
fn (Builder $builder): Builder => $builder->destinationUrl('https://fallback.com')
)
->make();
```

Added support for "when"

---

routes/web.php
src/Classes/Builder.php
src/Controllers/ShortURLController.php
src/Facades/ShortURL.php
tests/Unit/Controllers/ShortURLControllerTest.php
tests/Unit/Controllers/ShortURLDisableRouteTest.php

This PR fixes a bug that was caused by the default short URL route being registered before the routes in the application's `web.php` file. The route was acting as a catch-all route and always resulting in a 404 response.
This PR adds a new `ShortURL::routes()` method that you can manually add to your application's routes. This means that you can disable the route from being automatically registered and then register it yourself at the bottom of your routes file.
We're also changing the way the default route is handled if the `disable_default_route` config value is disabled. Previously, if the field was disabled, we would handle this inside the `ShortURLController` and return a 404 response. Now, if the field is disabled, we won't register the route at all, so we don't need to handle it in …

Fix `null` prefix bug

---

routes/web.php
src/Classes/Builder.php

I added the condition for registering the package's route in the `routes` method, but this meant that you couldn't manually register the routes yourself. I've now lifted this condition out into the package's `web.php` file so that you can now manually register the routes.

Lift condition into the package's route file

---

README.md
config/short-url.php
src/Classes/Builder.php
src/Classes/Validation.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Classes/ResolverTest.php
tests/Unit/Classes/ValidationTest.php
tests/Unit/Controllers/ShortURLControllerEmptyPrefixTest.php
tests/Unit/Controllers/ShortURLControllerPrefixTest.php
tests/Unit/Controllers/ShortURLControllerTest.php
tests/Unit/Controllers/ShortURLDisableRouteTest.php
tests/Unit/Models/ShortURL/TrackingEnabledTest.php
tests/Unit/Models/ShortURL/TrackingFieldsTest.php

This PR is to add an option to configure a **default_url** that is used in the **default_short_url** generator.
- Change is backwards-compatible.
- Change offers more flexibility when for example using a Tenancy package.

Added default_url config option

---

src/Models/ShortURL.php
src/Models/ShortURLVisit.php

As the title says, this is just a small change that moves the `dates` property to the `$casts` property . It was deprecated in an earlier release and has been removed for Laravel 10. 
Here is the relevant entry in the upgrade guide:
https://laravel.com/docs/10.x/upgrade#model-dates-property

Moved dates to casts for compatibility with Laravel 10

---

composer.json
src/Classes/Builder.php

This PR just allows for v5 of `hashids/hashids` to be used. v5 mostly adds types ([changelog](https://github.com/vinkla/hashids/blob/master/CHANGELOG.md)). It also removes support for PHP 8.0, which your library still supports. I wasn't sure how you'd like to handle that, so I haven't upgraded `composer.json` to `8.1` yet, but can obviously still do that.
There was one failing test after upgrading the hashids package due to the fact that the key generator was instantiated before the config values were validated and the type check for the key length then failed. I fixed those by validating first and then instantiating the generator after that. I guess it makes more sense this way anyways.

Allow hashids/hashids v5

---

database/migrations/2019_12_22_015115_create_short_urls_table.php
src/Classes/KeyGenerator.php

Fix collision and performance issue

---

README.md
config/short-url.php
database/migrations/2019_12_22_015115_create_short_urls_table.php
database/migrations/2019_12_22_015214_create_short_url_visits_table.php
database/migrations/2020_02_11_224848_update_short_url_table_for_version_two_zero_zero.php
database/migrations/2020_02_12_008432_update_short_url_visits_table_for_version_two_zero_zero.php
database/migrations/2020_04_10_224546_update_short_url_table_for_version_three_zero_zero.php
database/migrations/2020_04_20_009283_update_short_url_table_add_option_to_forward_query_params.php
src/Models/ShortURL.php
src/Models/ShortURLVisit.php
tests/Unit/Models/ShortURL/ShortURLTest.php
tests/Unit/Models/ShortURLVisit/ShortURLVisitTest.php

Allow override connection with an option in config/short-url.php without breaking changes.
it is useful when you use this package in an application with more than one connection that changes dynamically (such as a multitenat environment), but you always want to use the same connection

feat(config): allow override connection

---

README.md
src/Classes/Builder.php
tests/Unit/Classes/BuilderTest.php

This PR adds the ability to tap the `ShortURL` model before it is created via a `beforeCreate` method so that additional columns that applications may need can be set.
For example, my application needs to associate Short URL's to companies (via a `company_id`), which I've added to the published `short_urls` table migration. However, there's no way to set this relation during creation, so the `company_id` column must be nullable in the migration, even though it's actually required in my application for each Short URL created.
Adding a callback allows direct access to the `ShortURL` model prior to its creation, so that a `company_id` can be associated and be non-nullable.
```php
use AshAllenDesign\ShortURL\Models\ShortURL;
use AshAllenDesign\ShortURL\Facades\ShortURL as ShortUrlBuilder;
// …
```

Add ability to tap `ShortURL` model before creation

---

src/Facades/ShortURL.php

While building URL's I noticed some methods were missing (such as the `Conditionable` trait methods, `generateKeyUsing`, etc.) and some return types being incorrect (returning `self` instead of `Builder`), so I generated the annotations using Laravel's official [Facade Documenter](https://github.com/laravel/facade-documenter) via the below:
```bash
composer require stevebauman/autodoc-facades --dev
```
```bash
php -f vendor/bin/facade.php -- \
AshAllenDesign\\ShortURL\\Facades\\ShortURL
```
```bash
composer remove stevebauman/autodoc-facades
```
Let me know if you'd like anything changed/adjusted. Thanks for your time! 🙏

Generate facade docs using official Laravel Facade Documenter

---

CHANGELOG.md
composer.json
src/Classes/Resolver.php
src/Classes/UserAgent/ParserPhpDriver.php
src/Interfaces/UserAgentDriver.php
src/Models/Factories/ShortURLVisitFactory.php
src/Providers/ShortURLProvider.php
tests/Unit/Classes/ResolverTest.php

This PR removes the `jenssegers/agent` package (which doesn't appear to be updated as much anymore) and switches over to the `whichbrowser/parser` package instead.
There is a breaking change here because we're no longer accepting an `Agent` argument for the `Resolver` class' constructor.

Switch user agent packages

---

src/Models/ShortURL.php
src/Models/ShortURLVisit.php

This PR removes the `dates` property from the models.
This property was removed in Laravel 10: https://laravel.com/docs/10.x/upgrade#model-dates-property

Remove "date" property

---

.gitignore
composer.json
phpunit.xml
tests/Unit/Classes/BuilderTest.php
tests/Unit/Classes/ResolverTest.php
tests/Unit/Classes/ValidationTest.php
tests/Unit/Controllers/ShortURLControllerEmptyPrefixTest.php
tests/Unit/Controllers/ShortURLControllerPrefixTest.php
tests/Unit/Controllers/ShortURLControllerTest.php
tests/Unit/Controllers/ShortURLDisableRouteTest.php
tests/Unit/Models/ShortURL/CastsTest.php
tests/Unit/Models/ShortURL/ShortURLFactoryTest.php
tests/Unit/Models/ShortURL/ShortURLTest.php
tests/Unit/Models/ShortURL/TrackingEnabledTest.php
tests/Unit/Models/ShortURL/TrackingFieldsTest.php
tests/Unit/Models/ShortURLVisit/CastsTest.php
tests/Unit/Models/ShortURLVisit/ShortURLTest.php
tests/Unit/Models/ShortURLVisit/ShortURLVisitFactoryTest.php
tests/Unit/Models/ShortURLVisit/ShortURLVisitTest.php

This pull request contains changes for upgrading to [PHPUnit 10](https://phpunit.de/announcements/phpunit-10.html) automated by the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10).
**Before merging**, you need to:
- Checkout the `shift-117366` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Run your tests suite: `vendor/bin/phpunit`
If there were changes you felt could have been automated, please reply to the follow-up email with your feedback or on [Twitter](https://twitter.com/laravelshift).

PHPUnit 10 Shift

---

composer.json
src/Classes/Validation.php
src/Facades/ShortURL.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Classes/ResolverTest.php
tests/Unit/Classes/ValidationTest.php

This PR switches over to using `ashallendesign/laravel-config-validator`. I'm a little biased, but I feel like this might be a more robust way of validating the config that will make future maintenance a little easier 😄

Config validation updates

---

README.md

Just a small typo in `README.md` conditionals section.

Extra `)` in conditionals section of the docs

---

src/Classes/Builder.php
src/Models/ShortURL.php
src/Models/ShortURLVisit.php
tests/Unit/Classes/BuilderTest.php
tests/Unit/Models/ShortURL/CastsTest.php
tests/Unit/Models/ShortURLVisit/CastsTest.php

Replaces #284.
Recap: Currently the package breaks if your app has configured the `Date` facade to use `CarbonImmutable` instead of `Carbon` (as per [this blog post by Michael Dyrynda](https://dyrynda.com.au/blog/laravel-immutable-dates)).
To get it working is a one-line fix - changing one instance of `now()` to `Carbon::now()` in the `Builder` class.
Some comments/caveats:
- The reason no other changes are needed is because of Eloquent's casting magic. It ensures that _all_ `datetime` properties on Eloquent models contain an object of the correct class (either `Carbon` or `CarbonImmutable`, depending on how you've configured the `Date` facade), no matter what was used to set them.
- However, that also means the doc blocks for the `ShortURL` and `ShortURLVisit` models are incorrect: all …

Fix error when app is set to use CarbonImmutable

---

src/Classes/UserAgent/ParserPhpDriver.php
tests/Unit/Classes/ResolverTest.php

This PR should fix issue: https://github.com/ash-jc-allen/short-url/issues/294
The underlying package can't determine the OS from this user agent string:
```text
Mozilla/4.0 (compatible; MSIE 6.0; ) Opera/UCWEB7.0.2.37/28/999
```
The package's code makes it appear that the field will always be set, so I never took into account it not being set. I've updated this now to handle those situations 🙂

Fix bug where the OS name cannot be determined from the user agent

---

src/Classes/KeyGenerator.php

In some versions MySQL ShortURL::max('id') will be a string (like "2") and we will get an error.

ShortURL::max('id') alway integer
